version: '3.8'

services:
  blog:
    container_name: "blog"
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - blog_net
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.local.env
    networks:
      - blog_net

volumes:
  postgres_data:

networks:
  blog_net:
    driver: bridge
